# Generated by Django 6.0.2 on 2026-02-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('recorrencia', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('despesa_fixa', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('fonte_recursos', models.CharField(max_length=100)),
            ],
        ),
    ]
