# Generated by Django 6.0.2 on 2026-02-13 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
